# Generated by Django 5.0.12 on 2025-03-10 14:01
# https://github.com/hcientist/django_local_library/blob/main/catalog/migrations/0003_data_migration_seed_books_20250208_2221.py

from django.db import migrations


def seed_course(apps, schema_editor):
    Course = apps.get_model("thoughtswap", "Course")
    # see how i did things in the local library https://github.com/hcientist/django_local_library/blob/main/catalog/migrations/0003_data_migration_seed_books_20250208_2221.py


class Migration(migrations.Migration):
    dependencies = [
        ("thoughtswap", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_course),
    ]
