# Generated by Django 5.0.11 on 2025-03-24 13:43
# https://github.com/hcientist/django_local_library/blob/main/catalog/migrations/0003_data_migration_seed_books_20250208_2221.py
# https://docs.djangoproject.com/en/5.1/topics/migrations/#data-migrations
from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_mvp(apps, schema_editor):
    Course = apps.get_model("thoughtswap", "Course")
    User = apps.get_model("users", "User")
    Enrollment = apps.get_model("thoughtswap", "Enrollment")
    Prompt = apps.get_model("thoughtswap", "Prompt")
    Thought = apps.get_model("thoughtswap", "Thought")
    PromptUse = apps.get_model("thoughtswap", "PromptUse")
    Session = apps.get_model("thoughtswap", "Session")

    # create a teacher
    teacher = User.objects.create_user(
        username="teacher",
        email="teacher@thoughtswap.org",
        password="teacher",
    )
    teacher.first_name = "Teacher"
    teacher.last_name = "User"
    teacher.save()

    # create a second teacher
    teacher2 = User.objects.create_user(
        username="teacher2",
        email="teacher2@thoughtswap.org",
        password="teacher",
    )
    teacher.first_name = "Teacher"
    teacher.last_name = "User"
    teacher.save()

    # create a course
    course = Course.objects.create(
        title="Example Course CS 455",
        creator=teacher,
    )

    course2 = Course.objects.create(
        title="Example Course CS 227",
        creator=teacher2,
    )

    # enroll the teacher in the course
    Enrollment.objects.create(
        user=teacher,
        course=course,
        role="f",
    )

    # enroll the teacher2 in the course
    Enrollment.objects.create(
        user=teacher2,
        course=course2,
        role="f",
    )

    # create a student
    student1 = User.objects.create_user(
        username="student1",
        email="student1@thoughtswap.org",
        password="student",
    )
    # student1.first_name = "Student1"
    # student1.last_name = "User"
    # student1.save()

    student2 = User.objects.create_user(
        username="student2",
        email="student2@thoughtswap.org",
        password="student",
        # first_name = "Student2",
        # last_name = "User"
    )
    # student2.first_name = "Student2"
    # student2.last_name = "User"
    # student2.save()

    Enrollment.objects.create(
        user=student1,
        course=course,
        role="s",
    )
    Enrollment.objects.create(
        user=student2,
        course=course,
        role="s",
    )

    # create a prompt
    prompt = Prompt.objects.create(
        author=teacher,
        content="Example Prompt - Edward Snowden patriot or traitor?",
    )

    # create a session
    draft_session = Session.objects.create(
        course=course,
        state="a",
        begin="2025-04-27 01:16:53.260222+00:00",
    )

    prompt_use = PromptUse.objects.create(
        prompt=prompt,
        session=draft_session,
    )

    Thought.objects.create(
        prompt_use=prompt_use,
        author=student1,
        content="I think Edward Snowden is a patriot.",
    )
    Thought.objects.create(
        prompt_use=prompt_use,
        author=student2,
        content="I think Edward Snowden is a traitor.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("thoughtswap", "0002_prompt_session_promptuse_thought"),
    ]

    operations = [
        migrations.RunPython(seed_mvp),
    ]
