# Generated by Django 5.0.12 on 2025-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0003_seed_example_model_instances_20250324_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('a', 'Active'), ('c', 'Closed'), ('d', 'Draft')], default='a', help_text='Session state', max_length=1),
        ),
    ]
