# Generated by Django 5.0.12 on 2025-03-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0004_alter_session_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='thoughtswap.course'),
        ),
    ]
