# Generated by Django 5.0.12 on 2025-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0007_alter_session_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptuse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
