# Generated by Django 5.0.12 on 2025-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0009_session_is_swapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='in_bank',
            field=models.BooleanField(default=False),
        ),
    ]
