# Generated by Django 5.0.12 on 2025-05-05 13:37

from django.db import migrations

def seed_prompt_to_bank(apps, schema_editor):
    Prompt = apps.get_model('thoughtswap', 'Prompt')

    # Assuming you have a user with ID 1 to assign as the author

    # Create a new prompt instance
    prompt = Prompt.objects.all().last()
    prompt.in_bank = True
    prompt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtswap', '0010_prompt_in_bank'),
    ]

    operations = [
        migrations.RunPython(seed_prompt_to_bank),
    ]
