# Generated by Django 5.0.12 on 2025-05-05 13:43

from django.db import migrations


def add_fac_group_to_teacher_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Group = apps.get_model("auth", "Group")
    FACILITATOR_GRP_NAME = "Facilitator"
    facilitator_grp = Group.objects.create(name=FACILITATOR_GRP_NAME)

    # Get all users who are teachers (role 'f')
    teachers = User.objects.filter(enrollment__role="f")

    # Add the 'facilitator' group to each teacher
    for teacher in teachers:
        if not teacher.groups.filter(name=FACILITATOR_GRP_NAME).exists():
            teacher.groups.add(facilitator_grp)
            teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ("thoughtswap", "0011_prompt_in_bank_20250505_0937"),
    ]

    operations = [
        migrations.RunPython(add_fac_group_to_teacher_users),
    ]
