# Generated by Django 5.0.12 on 2025-02-27 19:16

import thoughtswap.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_prompt_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=thoughtswap.users.models.generate_unique_code, max_length=6, unique=True),
        ),
    ]
